### ISSUE TITLE
RNN issue

### ISSUE THREAD

**Issue by ShuvenduBikash** [lanpa/tensorboardX#174]
How can I make it work with RNN? I tried it with GRU to `add_graph(model, data)` which failed.

```
assert n.scopeName() != '', '{} has empty scope name'.format(n)

AssertionError: %29 : Dynamic = onnx::Shape(%10)
has empty scope name
```

**Comment by lanpa** [comment]
Please post your network so I can check on this, thanks.

**Comment by yaojialuo** [comment]
with SummaryWriter(comment='LSTM',log_dir=r"E:\study\ML\pytorch\log") as w:
    torch.manual_seed(1)
    lstm = nn.LSTM(3, 3)
    input = torch.ones(1, 3)
    hidden = (torch.randn(1, 1, 3),
              torch.randn(1, 1, 3))
    w.add_graph(lstm, input.view(1, 1, -1))

promt:
"E:\Program Files\Anaconda3\envs\tensorflow\python.exe" E:/study/ML/pytorch/pytorch-beginner/tensorbordx/demo
Traceback (most recent call last):
  File "E:/study/ML/pytorch/pytorch-beginner/tensorbordx/demo", line 20, in <module>
    w.add_graph(lstm, input.view(1, 1, -1))
  File "E:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorboardX\writer.py", line 499, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "E:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorboardX\pytorch_graph.py", line 102, in graph
    list_of_nodes = parse(graph)
  File "E:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorboardX\pytorch_graph.py", line 24, in parse
    assert n.scopeName() != '', '{} has empty scope name'.format(n)
AssertionError: %23 : Dynamic = onnx::Shape(%0)
 has empty scope name
