### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorboardX'

### ISSUE THREAD

**Issue by isalirezag** [lanpa/tensorboardX#182]
I tried to install tensorboardX and it shows that it is installed successfully:
![image](https://user-images.githubusercontent.com/12434910/42129439-88443f6e-7c92-11e8-8967-c75cda4261e0.png)

![image](https://user-images.githubusercontent.com/12434910/42129437-7f969844-7c92-11e8-98b9-d673a8b0a623.png)

```
Collecting git+https://github.com/lanpa/tensorboard-pytorch
  Cloning https://github.com/lanpa/tensorboard-pytorch to /tmp/pip-req-build-3a20nz_z
Requirement already satisfied (use --upgrade to upgrade): tensorboardX==1.2 from git+https://github.com/lanpa/tensorboard-pytorch in ./.local/lib/python3.5/site-packages
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from tensorboardX==1.2) (1.13.3)
Requirement already satisfied: protobuf>=0.3.2 in /usr/local/lib/python3.5/dist-packages (from tensorboardX==1.2) (3.4.0)
Requirement already satisfied: six in /usr/local/lib/python3.5/dist-packages (from tensorboardX==1.2) (1.11.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.5/dist-packages (from protobuf>=0.3.2->tensorboardX==1.2) (36.6.0)
Building wheels for collected packages: tensorboardX
  Running setup.py bdist_wheel for tensorboardX ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-un2dc33o/wheels/84/b5/d9/7fdb3057d8ab54436a7f143a8f33ee45e7163482e14a805b26
Successfully built tensorboardX
```
but then it is not installed and everytime i wanna use it it gives me error:
```
>>> from tensorboardX import SummaryWriter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorboardX'
```

**Comment by lanpa** [comment]
What is the output of `pip list|grep tensor`?

**Comment by isalirezag** [comment]
@lanpa What does this command do?
The output is:
```
tensorboard                   1.8.0                 
tensorboardX                  1.2                   
tensorflow                    1.8.0                 
tensorflow-gpu                1.8.0                 
tensorflow-tensorboard        1.5.1 
```

**Comment by lanpa** [comment]
Do you mean `import tensorflow ` results in 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorboardX'
```

btw, the following packages might conflict 
tensorboard                   1.8.0  
tensorflow                    1.8.0                 
tensorflow-gpu                1.8.0                 
tensorflow-tensorboard        1.5.1 
you should uninstall them and 
`pip install tensorflow-gpu` (which gives you tensorflow-gpu and tensorboard)

**Comment by isalirezag** [comment]
Yes that is what i meant.
Okay I will try that again

**Comment by engmubarak48** [comment]
I think this happens when pip and conda installation of TensorFlow conflicts. Conda installation of TensorFlow and tensorboardX works for me.
