### ISSUE TITLE
How to deal with 'VariableType::ID() not implemented' issue with custom layers?

### ISSUE THREAD

**Issue by protossw512** [lanpa/tensorboardX#189]
I am using a custom layer in my model, below is the detailed implementation:

```python
import pdb
import torch
import numpy as np
import torch.nn as nn
from tensorboardX import SummaryWriter
class AddCoordsTh(nn.Module):
    def __init__(self, x_dim=64, y_dim=64, with_r=False):
        super(AddCoordsTh, self).__init__()
        self.x_dim = x_dim
        self.y_dim = y_dim
        self.with_r = with_r

    def forward(self, input_tensor):
        """
        input_tensor: (batch, c, x_dim, y_dim)
        """
        batch_size_tensor = input_tensor.shape[0]

        xx_ones = torch.ones([1, self.y_dim], dtype=torch.int32)
        xx_ones = xx_ones.unsqueeze(-1)

        xx_range = torch.arange(self.x_dim, dtype=torch.int32).unsqueeze(0)
        xx_range = xx_range.unsqueeze(1)

        xx_channel = torch.matmul(xx_ones, xx_range)
        xx_channel = xx_channel.unsqueeze(-1)

        yy_ones = torch.ones([1, self.x_dim], dtype=torch.int32)
        yy_ones = yy_ones.unsqueeze(1)

        yy_range = torch.arange(self.y_dim, dtype=torch.int32).unsqueeze(0)
        yy_range = yy_range.unsqueeze(-1)

        yy_channel = torch.matmul(yy_range, yy_ones)
        yy_channel = yy_channel.unsqueeze(-1)

        xx_channel = xx_channel.permute(0, 3, 2, 1)
        yy_channel = yy_channel.permute(0, 3, 2, 1)

        xx_channel = xx_channel.float() / (self.x_dim - 1)
        yy_channel = yy_channel.float() / (self.y_dim - 1)

        xx_channel = xx_channel * 2 - 1
        yy_channel = yy_channel * 2 - 1

        xx_channel = xx_channel.repeat(batch_size_tensor, 1, 1, 1)
        yy_channel = yy_channel.repeat(batch_size_tensor, 1, 1, 1)

        if input_tensor.is_cuda:
            xx_channel = xx_channel.cuda()
            yy_channel = yy_channel.cuda()
        ret = torch.cat([input_tensor, xx_channel, yy_channel], dim=1)

        if self.with_r:
            rr = torch.sqrt(torch.pow(xx_channel - 0.5, 2) + torch.pow(yy_channel - 0.5, 2))
            if input_tensor.is_cuda:
                rr = rr.cuda()
            ret = torch.cat([ret, rr], dim=1)

        return ret

class CoordConvTh(nn.Module):
    """CoordConv layer as in the paper."""
    def __init__(self, x_dim, y_dim, with_r, *args, **kwargs):
        super(CoordConvTh, self).__init__()
        self.addcoords = AddCoordsTh(x_dim=x_dim, y_dim=y_dim, with_r=with_r)
        self.conv = nn.Conv2d(*args, **kwargs)

    def forward(self, input_tensor):
        ret = self.addcoords(input_tensor)
        ret = self.conv(ret)
        return ret

class Demo(nn.Module):

    def __init__(self):
        super(Demo, self).__init__()
        self.coordconv = CoordConvTh(64, 64, True, 13, 10,
                                     kernel_size=1, stride=1, padding=0)
    def forward(self, x):
        x = self.coordconv(x)
        return x

writer = SummaryWriter('./')
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = Demo()
model.to(device)
dummy_input = torch.ones(10, 10, 64, 64).to(device)
writer.add_graph(model, (dummy_input,))
```

Then I get error: 
```
Traceback (most recent call last):
  File "test_graph.py", line 93, in <module>
    writer.add_graph(model, (dummy_input,))
  File "/home/Xinyao/Pytorch/lib/python2.7/site-packages/tensorboardX/writer.py", line 419, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/Xinyao/Pytorch/lib/python2.7/site-packages/tensorboardX/graph.py", line 85, in graph
    list_of_nodes = parse(graph)
  File "/home/Xinyao/Pytorch/lib/python2.7/site-packages/tensorboardX/graph.py", line 28, in parse
    attrs = {k: n[k] for k in n.attributeNames()}
  File "/home/Xinyao/Pytorch/lib/python2.7/site-packages/tensorboardX/graph.py", line 28, in <dictcomp>
    attrs = {k: n[k] for k in n.attributeNames()}
  File "/home/Xinyao/Pytorch/lib/python2.7/site-packages/torch/onnx/utils.py", line 444, in _node_getitem
    return getattr(self, sel)(k)
RuntimeError: VariableType::ID() not implemented
```

I am guessing this is due to the new layer. I noticed someone else also had similar error with constant and the issue had been fixed then. I am trying to get around this issue but with limited knowledge I am not sure where to start. If someone could help me figure out it or point out the direction I could work on, it would be great.

tensorboardX: 1.2 installed with pip
pytorch: 0.4
python: 2.7

**Comment by protossw512** [comment]
@pluiez 
Tried:
'''
pip install git+https://github.com/lanpa/tensorboard-pytorch
'''
Also no luck

**Comment by h-jia** [comment]
please make sure you installed both tensorboard and tensorboard via 
`pip install`
Otherwise you will get this error.

You are welcome~

**Comment by protossw512** [comment]
@h-jia 
Thanks for reminding me, and yes I did use pip instead of conda, standard and I could run it with standard pytorch laryers as well.

**Comment by protossw512** [comment]
I tried to remove old installation and use `pip install git+https://github.com/lanpa/tensorboardX.git` and it worked. Seems like the instruction is using the old repository address?
