### ISSUE TITLE
Incompatible with bleeding edge version of PyTorch

### ISSUE THREAD

**Issue by pluiez** [lanpa/tensorboardX#190]
Hi, since torch.stack and torch.le operator is not supported in torch.onnx of version 0.4.0., I just installed pytorch from source and its version is 0.5.0a0+604f7e9. 

Then I ran the demo_graph.py and the following error is raised:
```
Traceback (most recent call last):
  File "demo_graph.py", line 55, in <module>
    w.add_graph(model, (dummy_input, ))
  File "/home/tqri/tensorboard-pytorch/tensorboardX/writer.py", line 499, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/tqri/tensorboard-pytorch/tensorboardX/pytorch_graph.py", line 96, in graph
    torch.onnx._optimize_trace(trace, False)
  File "/home/tqri/anaconda2/envs/py36/lib/python3.6/site-packages/torch/onnx/__init__.py", line 41, in _optimize_trace
    trace.set_graph(utils._optimize_graph(trace.graph(), operator_export_type))
  File "/home/tqri/anaconda2/envs/py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 106, in _optimize_graph
    if operator_export_type != OperatorExportTypes.RAW:
TypeError: __ne__(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C._onnx.OperatorExportTypes, arg0: torch._C._onnx.OperatorExportTypes) -> bool

Invoked with: OperatorExportTypes.RAW, False
```
Any ideas to solve this problem?

**Comment by lanpa** [comment]
Since pytorch changes fast and I don't have much time, I will have to wait for the stable release and then look into it.

**Comment by fernandocamargoti** [comment]
@lanpa, it seems it's happening with 0.4.1 too.

**Comment by lanpa** [comment]
Hi, 0.4.1 should be solved by install new pip release. @pluiez Can you have a try on 0.5?

**Comment by fernandocamargoti** [comment]
Hello, @lanpa. It's working!
