### ISSUE TITLE
Importing tensorboardX after importing tensorboard fails

### ISSUE THREAD

**Issue by universome** [lanpa/tensorboardX#206]
I'm trying to run tensorboard from python like proposed in [this SoF answer](https://stackoverflow.com/a/49555937/2685677), but importing tensorboardX afterwards fails with the following error:
```
Traceback (most recent call last):
    from tensorboard import default                                                                                                                                                  │  File "<stdin>", line 1, in <module>
  File "/cephfs/home/skorokhodov/pyvenvs/zoo/lib/python3.6/site-packages/tensorboard/default.py", line 46, in <module>                                                               │  File "/cephfs/home/skorokhodov/pyvenvs/zoo/lib/python3.6/site-packages/tensorboardX/__init__.py", line 4, in <module>
    from tensorboard.plugins.pr_curve import pr_curves_plugin                                                                                                                        │    from .writer import FileWriter, SummaryWriter
  File "/cephfs/home/skorokhodov/pyvenvs/zoo/lib/python3.6/site-packages/tensorboard/plugins/pr_curve/pr_curves_plugin.py", line 27, in <module>                                     │  File "/cephfs/home/skorokhodov/pyvenvs/zoo/lib/python3.6/site-packages/tensorboardX/writer.py", line 28, in <module>
    from tensorboard.plugins.pr_curve import metadata                                                                                                                                │    from .summary import scalar, histogram, image, audio, text, pr_curve, pr_curve_raw, video
  File "/cephfs/home/skorokhodov/pyvenvs/zoo/lib/python3.6/site-packages/tensorboard/plugins/pr_curve/metadata.py", line 22, in <module>                                             │  File "/cephfs/home/skorokhodov/pyvenvs/zoo/lib/python3.6/site-packages/tensorboardX/summary.py", line 48, in <module>
    from tensorboard.plugins.pr_curve import plugin_data_pb2                                                                                                                         │    from .src.plugin_pr_curve_pb2 import PrCurvePluginData
  File "/cephfs/home/skorokhodov/pyvenvs/zoo/lib/python3.6/site-packages/tensorboard/plugins/pr_curve/plugin_data_pb2.py", line 22, in <module>                                      │  File "/cephfs/home/skorokhodov/pyvenvs/zoo/lib/python3.6/site-packages/tensorboardX/src/plugin_pr_curve_pb2.py", line 22, in <module>
    serialized_pb=_b('\n.tensorboard/plugins/pr_curve/plugin_data.proto\x12\x0btensorboard\"<\n\x11PrCurvePluginData\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x16\n\x0enum_threshol│    serialized_pb=_b('\n&tensorboardX/src/plugin_pr_curve.proto\x12\x0btensorboard\"<\n\x11PrCurvePluginData\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x16\n\x0enum_thresholds\x18\
ds\x18\x02 \x01(\rb\x06proto3')                                                                                                                                                      │x02 \x01(\rb\x06proto3')
  File "/cephfs/home/skorokhodov/pyvenvs/zoo/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 878, in __new__                                                        │  File "/cephfs/home/skorokhodov/pyvenvs/zoo/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 878, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)                                                                                                                    │    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!                                                                                                                           │TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorboard/plugins/pr_curve/plugin_data.proto":                                                                                                  │Invalid proto descriptor for file "tensorboardX/src/plugin_pr_curve.proto":
  tensorboard.PrCurvePluginData.version: "tensorboard.PrCurvePluginData.version" is already defined in file "tensorboardX/src/plugin_pr_curve.proto".                                │  tensorboard.PrCurvePluginData.version: "tensorboard.PrCurvePluginData.version" is already defined in file "tensorboard/plugins/pr_curve/plugin_data.proto".
  tensorboard.PrCurvePluginData.num_thresholds: "tensorboard.PrCurvePluginData.num_thresholds" is already defined in file "tensorboardX/src/plugin_pr_curve.proto".                  │  tensorboard.PrCurvePluginData.num_thresholds: "tensorboard.PrCurvePluginData.num_thresholds" is already defined in file "tensorboard/plugins/pr_curve/plugin_data.proto".
  tensorboard.PrCurvePluginData: "tensorboard.PrCurvePluginData" is already defined in file "tensorboardX/src/plugin_pr_curve.proto".                                                │  tensorboard.PrCurvePluginData: "tensorboard.PrCurvePluginData" is already defined in file "tensorboard/plugins/pr_curve/plugin_data.proto".
```

Code to reproduce:
```
from tensorboard import main as tb
import tensorboardX
```

I have the following library versions:
```
tensorboard==1.10.0
tensorboardX==1.2
```

**Comment by universome** [comment]
That solved the issue, thanks!

**Comment by gar1t** [comment]
I'm seeing this behavior in 1.8 / master, same steps to reproduce:

```
>>> from tensorboard import main as tb
>>> import tensorboardX
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorboardX/proto/plugin_mesh.proto":
  tensorboard.mesh.MeshPluginData.version: "tensorboard.mesh.MeshPluginData.version" is already defined in file "tensorboard/plugins/mesh/
plugin_data.proto"
```

As well as the other order:

```
>>> import tensorboardX
>>> from tensorboard import main as tb
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorboard/plugins/mesh/plugin_data.proto":
  tensorboard.mesh.MeshPluginData.version: "tensorboard.mesh.MeshPluginData.version" is already defined in file "tensorboardX/proto/plugin_mesh.proto".
```

tensorboard version 1.14.0

**Comment by gar1t** [comment]
#448 appears to have introduced this regression.
