### ISSUE TITLE
AssertionError: %30 : Dynamic = onnx::Shape(%8)  has empty scope name in add_graph()

### ISSUE THREAD

**Issue by hsluoyz** [lanpa/tensorboardX#229]
I'm writing a PyTorch LSTM model and want to use tensorboardX to visualize the graph.

But when I call ``writer.add_graph(rnn, r)``, I got error:

```bat
C:\Python36\python.exe I:/github_repos/botrainer/train.py
Traceback (most recent call last):
  File "I:/github_repos/botrainer/train.py", line 238, in <module>
    writer.add_graph(rnn, r, verbose=False)
  File "C:\Python36\lib\site-packages\tensorboardX\writer.py", line 520, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "C:\Python36\lib\site-packages\tensorboardX\pytorch_graph.py", line 104, in graph
    list_of_nodes = parse(graph)
  File "C:\Python36\lib\site-packages\tensorboardX\pytorch_graph.py", line 24, in parse
    assert n.scopeName() != '', '{} has empty scope name'.format(n)
AssertionError: %30 : Dynamic = onnx::Shape(%8)
 has empty scope name

Process finished with exit code 1
```

My env is:

```bat
C:\Users\xxx>python3 -V
Python 3.6.6

C:\Users\xxx>pip3 freeze
absl-py==0.4.1
astor==0.7.1
atomicwrites==1.2.1
attrs==18.2.0
colorama==0.3.9
cycler==0.10.0
gast==0.2.0
grpcio==1.15.0
kiwisolver==1.0.1
Markdown==2.6.11
matplotlib==2.2.3
more-itertools==4.3.0
numpy==1.14.5
Pillow==5.2.0
pluggy==0.7.1
protobuf==3.6.1
py==1.6.0
pyparsing==2.2.0
pytest==3.8.0
python-dateutil==2.7.3
pytz==2018.5
six==1.11.0
tensorboard==1.10.0
tensorboardX==1.4
tensorflow==1.10.0
termcolor==1.1.0
torch==0.4.1
torchvision==0.2.1
Werkzeug==0.14.1
```

After some debugging, it seems that the ``scope name`` for the main RNN model is empty. My code is: 

https://github.com/hsluoyz/botrainer/blob/39857ff57a5d7a7983cf969bb95f1bf123f88901/train.py#L237-L238

Can you help me solve this issue? Thanks.

**Comment by dfdazac** [comment]
I am getting this error as well. If you set `verbose=True` when calling `add_graph()` you might see that some of the nodes in the graph have not been assigned a scope, which is why the error is shown. I am not sure why such nodes are missing a scope.
