### ISSUE TITLE
Cannot observe anything besides embeddings Python 3.7 Pytorch 1.0 TensorBoard 1.10.0

### ISSUE THREAD

**Issue by Diego999** [lanpa/tensorboardX#233]
Hi,

I tried your demo.py with pytorch version 1.0 (last release) and tensorboard 1.10.0, both compiled for python 3.7 on a Mac. Unfortunately, I cannot see anything (scalars, graphs, etc) besides embeddings.

I also have this error when running tensorboard
```shell
Exception in thread Reloader:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorboard/backend/application.py", line 371, in _reload
    reload_multiplexer(multiplexer, path_to_run)
  File "/usr/local/lib/python3.7/site-packages/tensorboard/backend/application.py", line 338, in reload_multiplexer
    multiplexer.Reload()
  File "/usr/local/lib/python3.7/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 238, in Reload
    Worker()
  File "/usr/local/lib/python3.7/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 216, in Worker
    accumulator.Reload()
  File "/usr/local/lib/python3.7/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 170, in Reload
    self._ProcessEvent(event)
  File "/usr/local/lib/python3.7/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 318, in _ProcessEvent
    value = data_compat.migrate_value(value)
  File "/usr/local/lib/python3.7/site-packages/tensorboard/data_compat.py", line 57, in migrate_value
    return handler(value) if handler else value
  File "/usr/local/lib/python3.7/site-packages/tensorboard/data_compat.py", line 106, in _migrate_scalar_value
    tensor_proto = tf.make_tensor_proto(scalar_value)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 536, in make_tensor_proto
    append_fn(tensor_proto, proto_values)
  File "tensorflow/python/framework/fast_tensor_util.pyx", line 27, in tensorflow.python.framework.fast_tensor_util.AppendFloat32ArrayToTensorProto
  File "/usr/local/lib/python3.7/site-packages/google/protobuf/internal/containers.py", line 251, in append
    self._values.append(self._type_checker.CheckValue(value))
UnboundLocalError: local variable 'self' referenced before assignment
```
Is there a hack to make it work ?

Thanks !

**Comment by Diego999** [comment]
By building from source Tensorflow with python 3.7 on an Ubuntu machine, everything works like a charm. I guess that the OSX prebuilt Tensorflow is flawed

**Comment by orionr** [comment]
Hi @Diego999 - are you having issues with the PyTorch 1.0 prebuilt binaries or TensorFlow prebuilt binaries? Your title says PyTorch 1.0, so just checking - thanks.

**Comment by Diego999** [comment]
Hi,

Pytorch prebuilt as tensorflow is not yet officially ready for 3.7, some
hacks have to be done (dependency of protobuf and changing some variables
names “async” to “async1”.

-- 
Diego Antognini

From: Orion Reblitz-Richardson <notifications@github.com>
<notifications@github.com>
Reply: lanpa/tensorboardX
<reply@reply.github.com>
<reply@reply.github.com>
Date: 4 October 2018 at 20:49:45
To: lanpa/tensorboardX <tensorboardx@noreply.github.com>
<tensorboardx@noreply.github.com>
CC: Diego Antognini <diegoantognini@gmail.com> <diegoantognini@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [lanpa/tensorboardX] Cannot observe anything besides
embeddings Python 3.7 Pytorch 1.0 TensorBoard 1.10/11.0 (#233)

Hi @Diego999 <https://github.com/Diego999> - are you having issues with the
