### ISSUE TITLE
UnicodeDecodeError when adding PNG image

### ISSUE THREAD

**Issue by malmaud** [lanpa/tensorboardX#242]
Hi,
I have a PNG image encoded as a 'bytes' object in Python 3.6 and want to add it as an image. I'm seeing the following, though:

```
In [3]: type(i)
Out[3]: bytes

In [4]: import tensorboardX

In [5]: s=tensorboardX.SummaryWriter()

In [6]: s.add_image("x",i,0)
Traceback (most recent call last):
  File "/home/malmaud/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-3f765f0b4e46>", line 1, in <module>
    s.add_image("x",i,0)
  File "/home/malmaud/anaconda3/lib/python3.6/site-packages/tensorboardX/writer.py", line 412, in add_image
    self.file_writer.add_summary(image(tag, img_tensor), global_step, walltime)
  File "/home/malmaud/anaconda3/lib/python3.6/site-packages/tensorboardX/summary.py", line 203, in image
    tensor = tensor.astype(np.float32)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 0: ordinal not in range(128)
```

**Comment by lanpa** [comment]
https://tensorboardx.readthedocs.io/en/latest/tensorboard.html#tensorboardX.SummaryWriter.add_image

You have to pass torch.Tensor or numpy.array to this function.
