### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by DachaoLin** [lanpa/tensorboardX#267]
Hi, everyone, I recently used pytorch to trained a model and saw the results in tensorboardx.   

My code relevant to the summary:
```from tensorboardX import SummaryWriter  
train_summary_write = SummaryWriter(os.path.join(args.model_dir, 'train_events'))
eval_summary_write = SummaryWriter(os.path.join(args.model_dir, 'eval_events'))
train_summary_write.add_scalar(name, record[name] / total, epoch)
train_summary_write.add_scalar('loss', (record['cross_entropy'] + record['l2_loss']) / total, epoch)
train_summary_write.close()
eval_summary_write.close()
```
But got error:
```
Exception in thread ProjectorPluginIsActiveThread:
Traceback (most recent call last):
  File "/home/lin/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/lin/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lin/anaconda3/lib/python3.6/site-packages/tensorboard/plugins/projector/projector_plugin.py", line 296, in _determine_is_active
    if self.configs:
  File "/home/lin/anaconda3/lib/python3.6/site-packages/tensorboard/plugins/projector/projector_plugin.py", line 313, in configs
    run_path_pairs)
  File "/home/lin/anaconda3/lib/python3.6/site-packages/tensorboard/plugins/projector/projector_plugin.py", line 393, in _read_latest_config_files
    ckpt_path = _find_latest_checkpoint(logdir)
  File "/home/lin/anaconda3/lib/python3.6/site-packages/tensorboard/plugins/projector/projector_plugin.py", line 652, in _find_latest_checkpoint
    ckpt_path = tf.train.latest_checkpoint(os.path.join(dir_path, os.pardir))
  File "/home/lin/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_management.py", line 331, in latest_checkpoint
    ckpt = get_checkpoint_state(checkpoint_dir, latest_filename)
  File "/home/lin/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_management.py", line 268, in get_checkpoint_state
    coord_checkpoint_filename)
  File "/home/lin/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 300, in read_file_to_string
    return f.read()
  File "/home/lin/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 132, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/home/lin/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 100, in _prepare_value
    return compat.as_str_any(val)
  File "/home/lin/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 107, in as_str_any
    return as_str(value)
  File "/home/lin/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 80, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
Though I still can see the scalar graph in tensorboard.

my env:
pytorch 0.4.1
tensorboard 1.11.0
tensorboardx 1.4

Thanks!

**Comment by DachaoLin** [comment]
Thank you for your reply!
All the code I use for tensorboardx showed in first code box, I just run a `.py` without demo program,  and when I restart I already move the previous log away.
I tried examples in `tensorboardX/examples` folder , since there had no error.
