### ISSUE TITLE
tensorboardX add_graph() ImportError: cannot import name 'OperatorExportTypes'

### ISSUE THREAD

**Issue by Carl-Lei** [lanpa/tensorboardX#323]
when I used the add_graph(), I got the error 
```
Traceback (most recent call last):
  File "F:/PycharmProjects/Pytorch/cbam/show_model.py", line 17, in <module>
    writer.add_graph(model,(inputs,))
  File "E:\SoftWare\Anaconda3\lib\site-packages\tensorboardX\writer.py", line 566, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "E:\SoftWare\Anaconda3\lib\site-packages\tensorboardX\pytorch_graph.py", line 171, in graph
    from torch.onnx.utils import OperatorExportTypes
ImportError: cannot import name 'OperatorExportTypes'
```

my pytorch's version is 0.4.0, and tensorboardX's version is 1.6. 
How could I deal with it?

**Comment by lanpa** [comment]
pytorch 0.4.0 should be used with tensorboardX v1.4.
I will add a version check message for this.

**Comment by Carl-Lei** [comment]
how can I install the tensorboardX v1.4?Just "pip install tensorboardX=1.4"?
