### ISSUE TITLE
TypeError: Cannot handle this data type

### ISSUE THREAD

**Issue by Diligentfight** [lanpa/tensorboardX#375]
mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 832), '|u1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trainnoaspp.py", line 553, in <module>
    main()
  File "trainnoaspp.py", line 512, in main
    writer.add_image("image",bgr_img,global_step=i_iter)
  File "/data/yy.jiang/jiachang.guo/anaconda3/lib/python3.6/site-packages/tensorboardX/writer.py", line 427, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File "/data/yy.jiang/jiachang.guo/anaconda3/lib/python3.6/site-packages/tensorboardX/summary.py", line 216, in image
    image = make_image(tensor, rescale=rescale)
  File "/data/yy.jiang/jiachang.guo/anaconda3/lib/python3.6/site-packages/tensorboardX/summary.py", line 254, in make_image
    image = Image.fromarray(tensor)
  File "/data/yy.jiang/jiachang.guo/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2517, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type

**Comment by lanpa** [comment]
please follow the issue template.

**Comment by abenbihi** [comment]
If you are using V1.6, one solution may be to feed an image in the following format: C x H x W
