### ISSUE TITLE
exception in exporting graph data

### ISSUE THREAD

**Issue by gurvindersingh** [lanpa/tensorboardX#376]
**Describe the bug**
I am trying to export a simple [DL model](https://github.com/fastai/fastai/blob/release-1.0.47/fastai/tabular/models.py#L6) graph using tensorboardX. But i am getting this exception when making the call with `input_to_model` as `[tensor([[ 1, 10,  1]], device='cuda:0'), tensor([[-0.1078]], device='cuda:0')]`

```Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/site-packages/fastai/callbacks/tensorboard.py", line 227, in _queue_processor
    request.write()
  File "/opt/conda/lib/python3.6/site-packages/fastai/callbacks/tensorboard.py", line 417, in write
    self.tbwriter.add_graph(model=self.model, input_to_model=self.input_to_model)
  File "/opt/conda/lib/python3.6/site-packages/tensorboardX/writer.py", line 566, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/opt/conda/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 222, in graph
    trace, _ = torch.jit.get_trace_graph(model, args)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 197, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace)(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 252, in forward
    out = self.inner(*trace_inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x_cont'

```

As shown in the link model expects `x_cat` and `x_cont` which are in the input list as first and second input. TensorboardX method is called using [fast.ai callbacks](https://github.com/fastai/fastai/blob/master/fastai/callbacks/tensorboard.py#L81) and [later here](https://github.com/fastai/fastai/blob/master/fastai/callbacks/tensorboard.py#L417)

**Expected behavior**
I would like to see the model graph. The above code works just fine when using different model with a single tensor as input but when model has more than one input in forward phase i get the exception.

**Environment**
What is the result of 
`pip list|grep -E "torch|proto|tensor"`
protobuf                          3.6.1
tensorboard                       1.12.2
tensorboardX                      1.6
tensorflow                        1.12.0
tensorflow-gpu                    1.12.0
tensorflow-probability-gpu        0.4.0
torch                             1.0.1.post2
torchtext                         0.3.1
torchvision                       0.2.1

**Comment by lanpa** [comment]
Hi, let me list some possible errors here:
1. `device='cuda:0'` (both input and model should stay on cpu before exporting)
2. args should be tuple, not list.
3. did you install tensorboardX via `pip`, many bugs were fixed since v1.6.

**Comment by gurvindersingh** [comment]
i think the issue is 2 point. 1st and 3rd i have tried and works ok in different contexts when model only expcets a single input as `def forward(self, x:Tensor)` whereas in the current case model expects a tuple. I couldn't find a way to pass tuple to graphwriter. So if you have any pointer please let me know.

**Comment by lanpa** [comment]
https://github.com/lanpa/tensorboardX/blob/6e62d1c9805a2fa7f3b3bcee589f255057fde7f3/examples/demo_graph.py#L33
