### ISSUE TITLE
ImportError: cannot import name 'summary'

### ISSUE THREAD

**Issue by YangSN0719** [lanpa/tensorboardX#392]
(n2n) [410@mu01 noise2noise-master]$ python config.py validate --dataset-dir=datasets/kodak --network-snapshot=results/network_final-gaussian-n2c.pickle
Traceback (most recent call last):
  File "config.py", line 14, in <module>
    import validation
  File "/home/410/ysn/noise2noise-master/validation.py", line 16, in <module>
    import dnnlib.tflib.tfutil as tfutil
  File "/home/410/ysn/noise2noise-master/dnnlib/tflib/__init__.py", line 8, in <module>
    from . import autosummary
  File "/home/410/ysn/noise2noise-master/dnnlib/tflib/autosummary.py", line 28, in <module>
    from tensorboard import summary as summary_lib
ImportError: cannot import name 'summary'

**Comment by lanpa** [comment]
from tensorboard`X`
