### ISSUE TITLE
Cannot run demo_graph.py

### ISSUE THREAD

**Issue by Gouiaa** [lanpa/tensorboardX#423]
**Describe the bug**

**Minimal runnable code to reproduce the behavior**
```
demo_graph.py
```

**Expected behavior**
I expect to save the graph and visualize it using tensorboard

**Screenshots**
No results

**Environment**
What is the result of 
protobuf                 3.6.1      
tensorboard              1.9.0      
tensorboardX             1.6        
tensorflow               1.9.0      
torch                    0.4.1.post2
torchvision              0.2.1 

**Additional context**
**I got this error:**
Traceback (most recent call last):
  File "demo_graph.py", line 20, in <module>
    w.add_graph(LinearInLinear(), dummy_input, True)
  File "/home/rafikg/Downloads/tensorboardX-master/examples/tensorboardX/writer.py", line 672, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/rafikg/Downloads/tensorboardX-master/examples/tensorboardX/pytorch_graph.py", line 317, in graph
    _optimize_trace(trace, operator_export_type)
  File "/home/rafikg/Downloads/tensorboardX-master/examples/tensorboardX/pytorch_graph.py", line 243, in _optimize_trace
    trace.set_graph(_optimize_graph(trace.graph(), operator_export_type))
  File "/home/rafikg/Downloads/tensorboardX-master/examples/tensorboardX/pytorch_graph.py", line 251, in _optimize_graph
    torch._C._jit_pass_constant_propagation(graph)

**Comment by lanpa** [comment]
please use pytorch >1.0 or use the previous tensorboardX.

https://github.com/lanpa/tensorboardX/releases
