### ISSUE TITLE
add_graph error.

### ISSUE THREAD

**Issue by wangyarui** [lanpa/tensorboardX#446]
Hi,friends, I met some issues when i run add_graph. And other add_scalers I can add.
Pytorch:1.1.0
TensorboardX:1.7
Python:3.6
Thanks very much!

Issues:
```
Traceback (most recent call last):
  File "/home/Training_Log/oss_whole_body/visModel.py", line 14, in <module>
    SummaryWriter.add_graph(model,input,True)
  File "/home/venv/lib/python3.6/site-packages/tensorboardX/writer.py", line 569, in add_graph
    if not self.caffe2_enabled:
  File "/home/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'Fast2Pose_SE' object has no attribute 'caffe2_enabled'

Process finished with exit code 1
```
Code:
```
import torch
from tensorboardX import SummaryWriter

from src.models.testPose import createModel


input=torch.rand(16,3,320,256)

writer = SummaryWriter('./testVis')

model=createModel()
model.load_state_dict(torch.load('XXX.pth'))

SummaryWriter.add_graph(model,input,True)
```

**Comment by lanpa** [comment]
It should be something like:

`writer.add_graph(model, input, True)`

**Comment by wangyarui** [comment]
@lanpa Thanks very much! It's my ignore.
