### ISSUE TITLE
Why did I fail to visualize?

### ISSUE THREAD

**Issue by LGZY432** [lanpa/tensorboardX#453]
gb = torch.zeros(84,84,3)

with torch.cuda.device(1):
    rgb = rgb.cuda()
    h1 = Variable(torch.zeros(1, 64).cuda())
    c1 = Variable(torch.zeros(1, 64).cuda())
    h2 = Variable(torch.zeros(1, 256).cuda())
    c2 = Variable(torch.zeros(1, 256).cuda())
    
    prev_reward = Variable(torch.zeros(1,1).cuda())
    prev_act = Variable(torch.zeros(1,8).cuda())
    prev_vel = Variable(torch.zeros(1,6).cuda())

currentPath = os.path.dirname(os.path.realpath(__file__))
load_model_dir = currentPath+'/trained_models/global_A3Clstm.pt'
print(load_model_dir)

global_A3Clstm = A3Clstm()
saved_state = torch.load(load_model_dir)
global_A3Clstm.load_state_dict(saved_state)
global_A3Clstm.eval()

writer = SummaryWriter(logdir='./log', comment='resnet18')
with writer:
    writer.add_graph(global_A3Clstm, [rgb.unsqueeze(0), prev_reward, prev_act, prev_vel, (h1, c1), (h2, c2)])

========================================================

Error occurs, No graph saved
Checking if it's onnx problem...
Your model cannot be exported by onnx, please report to onnx team
Traceback (most recent call last):
  File "1.py", line 50, in <module>
    writer.add_graph(global_A3Clstm, [rgb.unsqueeze(0), prev_reward, prev_act, prev_vel, (h1, c1), (h2, c2)])
  File "/home/gt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorboardX/writer.py", line 697, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/gt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorboardX/writer.py", line 137, in add_graph
    graph = graph_profile[0]
TypeError: 'GraphDef' object does not support indexing

**Comment by lanpa** [comment]
Please follow issue template
