### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'labels'

### ISSUE THREAD

**Issue by zhoulukuan** [lanpa/tensorboardX#473]
I used `writer.add_graph(model, (dump_int, ))` to draw the network and got this error:
```
Error occurs, No graph saved
Traceback (most recent call last):
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/tensorboardX/pytorch_graph.py", line 222, in graph
    trace, _ = torch.jit.get_trace_graph(model, args)
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 196, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace)(*args, **kwargs)
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 251, in forward
    out = self.inner(*trace_inputs)
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/data00/home/zhoulukuan/HRNet-Semantic-Segmentation/tools/../lib/utils/utils.py", line 34, in forward
    outputs = self.model(inputs)
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/data00/home/zhoulukuan/HRNet-Semantic-Segmentation/tools/../lib/models/seg_hrnet.py", line 423, in forward
    x = self.conv1(x)
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data00/home/zhoulukuan/HRNet-Semantic-Segmentation/tools/train.py", line 247, in <module>
    main()
  File "/data00/home/zhoulukuan/HRNet-Semantic-Segmentation/tools/train.py", line 166, in main
    writer_dict['writer'].add_graph(model, (dump_input, torch.zeros(1,473,473)))
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/tensorboardX/writer.py", line 566, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/tensorboardX/pytorch_graph.py", line 225, in graph
    _ = model(args)  # don't catch, just print the error message
  File "/data00/home/zhoulukuan/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'labels'
```
python: 3.7.3
tensorboardX: 1.6
torch: 1.0.0
In fact, I have tried torch==0.4.1 before. And the error is `AttributeError: 'function' object has no attribute 'graph'.
How to deal with it?

**Comment by lanpa** [comment]
`RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same` => The data should both on the cpu. Please use tensorboardX 1.8 instead.
