### ISSUE TITLE
AttributeError: 'function' object has no attribute 'graph'

### ISSUE THREAD

**Issue by zhangxiaodi** [lanpa/tensorboardX#474]
/home/znb/anaconda3/envs/pvNet/bin/python /home/znb/research/pvnet/demoGraph.py
Traceback (most recent call last):
  File "/home/znb/research/pvnet/demoGraph.py", line 20, in <module>
    w.add_graph(LinearInLinear(), dummy_input, True)
  File "/home/znb/anaconda3/envs/pvNet/lib/python3.6/site-packages/tensorboardX/writer.py", line 738, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/znb/anaconda3/envs/pvNet/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 241, in graph
    graph = trace.graph
AttributeError: 'function' object has no attribute 'graph'

Process finished with exit code 1

when i run the the demoGraph.py from the example of tensorBoardX. i meet this problem.
my pytorch is 0.4.1. 
tensorboard               1.14.0                 
tensorboardx              1.8                    
tensorflow                1.14.0                   
tensorflow-estimator      1.14.0

**Comment by lanpa** [comment]
Your pytorch version is too old for TBX 1.8

**Comment by zhangxiaodi** [comment]
thanks! when i convert the TBX to 1.4! the problem is missing!

**Comment by Devin879176** [comment]
File "demo_graph.py", line 20, in <module>
    w.add_graph(LinearInLinear(), dummy_input, True)
  File "/home/devin/tensorboardX/examples/tensorboardX/writer.py", line 774, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/devin/tensorboardX/examples/tensorboardX/pytorch_graph.py", line 249, in graph
    graph = trace.graph
AttributeError: 'function' object has no attribute 'graph'


how to solve the problem?
I changed  tensorboardx  to 1.4 but it does not work.

**Comment by Devin879176** [comment]
File "demo_graph.py", line 20, in <module>
    w.add_graph(LinearInLinear(), dummy_input, True)
  File "/home/devin/tensorboardX/examples/tensorboardX/writer.py", line 774, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/devin/tensorboardX/examples/tensorboardX/pytorch_graph.py", line 249, in graph
    graph = trace.graph
AttributeError: 'function' object has no attribute 'graph'


how to solve the problem?
I changed  tensorboardx  to 1.4 but it does not work.

**Comment by saravanan2611** [comment]
with keras.backend.get_session.graph.as_default():
AttributeError: 'function' object has no attribute 'graph'

I get this error while executing my django project. 
Please help me to clear this error.

**Comment by liuhuixiang-987** [comment]
Is there a good solution? I made the same mistake

**Comment by lanpa** [comment]
@saravanan2611 The keras graph is not supported. @liuhuixiang-987 What version are you using? Please feel free to open a new issue with the provided template.
