### ISSUE TITLE
ValueError: TracedModules don't support parameter sharing between modules

### ISSUE THREAD

**Issue by CatFootPrint** [lanpa/tensorboardX#509]
Hello!
I used the TensorboardX to obtain the graph of MegatronLM.
However, when I used the writer.add_graph(model, input), I encountered the error as follows:
`Traceback (most recent call last):
  File "pretrain_bert.py", line 624, in <module>
    main()
  File "pretrain_bert.py", line 559, in main
    w.add_graph(model,[torch.zeros(4,512),torch.zeros(4,512),torch.zeros(4,512),torch.zeros(4,512)])
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/tensorboardX/writer.py", line 738, in a                                                                       dd_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 24                                                                       0, in graph
    trace = torch.jit.trace(model, args)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 686, in tr                                                                       ace
    traced = _module_class(func, **executor_options)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1046, in i                                                                       nit_then_register
    original_init(self, *args, **kwargs)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1046, in i                                                                       nit_then_register
    original_init(self, *args, **kwargs)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1482, in _                                                                       _init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1046, in i                                                                       nit_then_register
    original_init(self, *args, **kwargs)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1482, in _                                                                       _init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1046, in i                                                                       nit_then_register
    original_init(self, *args, **kwargs)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1482, in _                                                                       _init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1046, in i                                                                       nit_then_register
    original_init(self, *args, **kwargs)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1482, in _                                                                       _init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1046, in i                                                                       nit_then_register
    original_init(self, *args, **kwargs)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1482, in _                                                                       _init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1046, in i                                                                       nit_then_register
    original_init(self, *args, **kwargs)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1469, in _                                                                       _init__
    check_unique(param)
  File "/home/z00487393/Applications/Virtualenv/MegatronLM_env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1461, in c                                                                       heck_unique
    raise ValueError("TracedModules don't support parameter sharing between modules")
ValueError: TracedModules don't support parameter sharing between modules
`
Could you please help me find the solution. 
Thanks a lot! Best wishes for you!

**Comment by lanpa** [comment]
https://github.com/pytorch/pytorch/issues/7904
We need to wait until pytorch supports this.
