### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PersistentOpEvaluator'

### ISSUE THREAD

**Issue by caiwjhi** [lanpa/tensorboardX#600]
I have installed tensorboardX in a miniconda envs where python is 3.7.7 and pytorch is 1.0 (cuda 8.0). And I get the fllowing error. I use Linux.
>tensorboard
tf.estimator package not installed.
tf.estimator package not installed.
Traceback (most recent call last):
  File "/usr/bin/tensorboard", line 6, in <module>
    from tensorboard.main import run_main
  File "/usr/lib/python2.7/site-packages/tensorboard/main.py", line 45, in <module>
    from tensorboard import default
  File "/usr/lib/python2.7/site-packages/tensorboard/default.py", line 38, in <module>
    from tensorboard.plugins.beholder import beholder_plugin
  File "/usr/lib/python2.7/site-packages/tensorboard/plugins/beholder/__init__.py", line 15, in <module>
    from tensorboard.plugins.beholder.beholder import Beholder
  File "/usr/lib/python2.7/site-packages/tensorboard/plugins/beholder/beholder.py", line 25, in <module>
    from tensorboard.plugins.beholder import im_util
  File "/usr/lib/python2.7/site-packages/tensorboard/plugins/beholder/im_util.py", line 89, in <module>
    class PNGDecoder(util.PersistentOpEvaluator):
AttributeError: 'module' object has no attribute 'PersistentOpEvaluator'

**Comment by lanpa** [comment]
Looks like you actually have `/usr/lib/python2.7/`. Please create a new python environment and install the required packages.
