### ISSUE TITLE
when i first import torch and then import tensorboardX, it seems wrong

### ISSUE THREAD

**Issue by myaxxxxx** [lanpa/tensorboardX#612]
when i first import torch and then import tensorboardX, it seems wrong,
############################
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/SuXiangDong/Language/anaconda3/envs/rsn/lib/python3.6/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/home/SuXiangDong/Language/anaconda3/envs/rsn/lib/python3.6/site-packages/tensorboardX/torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "/home/SuXiangDong/Language/anaconda3/envs/rsn/lib/python3.6/site-packages/tensorboardX/writer.py", line 16, in <module>
    from .event_file_writer import EventFileWriter
  File "/home/SuXiangDong/Language/anaconda3/envs/rsn/lib/python3.6/site-packages/tensorboardX/event_file_writer.py", line 28, in <module>
    from .proto import event_pb2
  File "/home/SuXiangDong/Language/anaconda3/envs/rsn/lib/python3.6/site-packages/tensorboardX/proto/event_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/SuXiangDong/Language/anaconda3/envs/rsn/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 48, in <module>
    from google.protobuf.pyext import _message
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/SuXiangDong/Language/anaconda3/envs/rsn/lib/python3.6/site-packages/google/protobuf/pyext/_message.cpython-36m-x86_64-linux-gnu.so)
##############################

But what confused me is when I first import tensorboardX and then import torch , it works.

my python is 3.6.2       GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
cuda is 9.2 and torch is 1.4.0+cu92

thanks

**Comment by myaxxxxx** [comment]
It's solved.
The Protobuf version is a little bit low just upgrade the version of protobuf.
