### ISSUE TITLE
EOFError multiprocessing

### ISSUE THREAD

**Issue by AliAlhasan2** [lanpa/tensorboardX#722]
I got this problem and I've been trying for a week to resolve this issue. Really need help i'm working on my Bachelor Thesis. Tank for helping

Traceback (most recent call last):
  File "/home/alhasan.ali/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/alhasan.ali/anaconda3/lib/python3.9/site-packages/tensorboardX/event_file_writer.py", line 202, in run
    data = self._queue.get(True, queue_wait_duration)
  File "/home/alhasan.ali/anaconda3/lib/python3.9/multiprocessing/queues.py", line 117, in get
    res = self._recv_bytes()
  File "/home/alhasan.ali/anaconda3/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/alhasan.ali/anaconda3/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/alhasan.ali/anaconda3/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError

**Comment by lanpa** [comment]
@AliAlhasan2 Please follow the issue format so that I can get more context about your issue. Thanks
